### PR TITLE
turn hugo theme into a submodule

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
switched to @karasz' fork

**Comment by amery** [comment]
added `github.com/jpi-oss/assets` as `src/assets` for usage with Hugo pipes

**Comment by amery** [comment]
assets work moved to its own PR. https://github.com/jpi-oss/jpi-oss-website/pull/6

**Review by karasz — CHANGES_REQUESTED** [review]
can you please re-push with the proper url? now it is ok.

**Comment by amery** [comment]
@karasz amended as requested

**Review by karasz — APPROVED** [review]
LGTM

**Pull request merged**
